// <auto-generated />
using System;
using GerenciadorProjetos.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GerenciadorProjetos.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260327180112_AddMembroTarefa")]
    partial class AddMembroTarefa
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.25");

            modelBuilder.Entity("GerenciadorProjetos.Models.Projeto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DataInicio")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataPrazo")
                        .HasColumnType("TEXT");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("GerenteResponsavelId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("GerenteResponsavelId");

                    b.ToTable("Projetos", (string)null);
                });

            modelBuilder.Entity("GerenciadorProjetos.Models.Tarefa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("MembroResponsavelId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PercentualConclusao")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Prioridade")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ProjetoId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("MembroResponsavelId");

                    b.HasIndex("ProjetoId");

                    b.ToTable("Tarefas", (string)null);
                });

            modelBuilder.Entity("GerenciadorProjetos.Models.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TipoUsuario")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Usuarios", (string)null);
                });

            modelBuilder.Entity("ProjetoUsuario", b =>
                {
                    b.Property<int>("EquipaId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ProjetosParticipadosId")
                        .HasColumnType("INTEGER");

                    b.HasKey("EquipaId", "ProjetosParticipadosId");

                    b.HasIndex("ProjetosParticipadosId");

                    b.ToTable("ProjetoEquipes", (string)null);
                });

            modelBuilder.Entity("GerenciadorProjetos.Models.Projeto", b =>
                {
                    b.HasOne("GerenciadorProjetos.Models.Usuario", "Gerente")
                        .WithMany()
                        .HasForeignKey("GerenteResponsavelId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Gerente");
                });

            modelBuilder.Entity("GerenciadorProjetos.Models.Tarefa", b =>
                {
                    b.HasOne("GerenciadorProjetos.Models.Usuario", "MembroResponsavel")
                        .WithMany()
                        .HasForeignKey("MembroResponsavelId");

                    b.HasOne("GerenciadorProjetos.Models.Projeto", "Projeto")
                        .WithMany()
                        .HasForeignKey("ProjetoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MembroResponsavel");

                    b.Navigation("Projeto");
                });

            modelBuilder.Entity("ProjetoUsuario", b =>
                {
                    b.HasOne("GerenciadorProjetos.Models.Usuario", null)
                        .WithMany()
                        .HasForeignKey("EquipaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GerenciadorProjetos.Models.Projeto", null)
                        .WithMany()
                        .HasForeignKey("ProjetosParticipadosId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
